# Generated by Django 4.1.4 on 2022-12-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_remove_mechanic_default_available_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="brief_description",
            field=models.TextField(blank=True),
        ),
    ]
