# Generated by Django 4.1.4 on 2022-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_remove_service_checking_plan_service_checking_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkingplan",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
