# Generated by Django 4.1.4 on 2022-12-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_id", models.CharField(blank=True, max_length=10)),
                ("publication_title", models.CharField(blank=True, max_length=50)),
                ("vehicle_brand", models.CharField(blank=True, max_length=20)),
                ("vehicle_model", models.CharField(blank=True, max_length=20)),
                ("vehicle_kilometers", models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
