# Generated by Django 4.1.4 on 2022-12-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_quoterequest_vehicle_kilometers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=20)),
                ("last_name", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=20)),
                ("state", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=20)),
                ("specialities", models.TextField(blank=True)),
                ("default_available_days", models.TextField(blank=True)),
                ("default_available_hours", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="seller_address_city",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="seller_address_country",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="seller_address_state",
            field=models.CharField(blank=20, max_length=20),
        ),
    ]
