# Generated by Django 4.1.4 on 2022-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_checkingplan_mechanicalworkshop_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="mechanic", name="default_available_days",),
        migrations.RemoveField(model_name="mechanic", name="default_available_hours",),
        migrations.AddField(
            model_name="checkingplan",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="avaialble_during_afternoon",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="available_during_morning",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="independent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="mechanicalworkshop",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
