# Generated by Django 4.1.4 on 2022-12-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_checkingplan_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mechanicalworkshop",
            name="distance_availability",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Distance dispuesto a realizar para revisar un vehiculo (en Kms)",
            ),
        ),
        migrations.RemoveField(model_name="service", name="checking_plan",),
        migrations.AddField(
            model_name="service",
            name="checking_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="services",
                to="pages.checkingplan",
            ),
        ),
    ]
