# Generated by Django 4.1.4 on 2023-01-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_mechanic_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="phone_number",
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="mechanic",
            name="checking_plans",
            field=models.ManyToManyField(
                related_name="mechanics", to="pages.checkingplan"
            ),
        ),
    ]
